### ISSUE TITLE
Error while executing tests

### ISSUE THREAD

**Issue by smiklosovic** [zegelin/ccm-extensions#1]
while running everywhere-strategy tests, these tests dont run with python2

```
[smiklosovic@E091-FED test]$ python2 ccm-test.py 
  File "ccm-test.py", line 21
    raise argparse.ArgumentTypeError(f'"{path}" must be a directory.')
                                                                    ^
SyntaxError: invalid syntax
```

When I execute it with python3, I get

```
[smiklosovic@E091-FED test]$ python3 ccm-test.py 3.11.8
INFO:__main__:Cluster directory is: /tmp/tmpf82olv_x/test-cluster
INFO:__main__:Dump directory is: /tmp/tmpf82olv_x/test-cluster/dumps
INFO:__main__:EverywhereStrategy JAR is: /home/smiklosovic/dev/cassandra-everywhere-strategy/target/instaclustr-everywhere-strategy-1.0-SNAPSHOT.jar
INFO:__main__:Setting up Cassandra cluster.
INFO:__main__:Starting cluster.
INFO:__main__:Applying CQL schema.
Traceback (most recent call last):
  File "ccm-test.py", line 81, in <module>
    ccm_cluster.apply_schema(args.schema)
  File "/usr/local/lib/python3.7/site-packages/ccm_extensions-0.1-py3.7.egg/ccm_extensions.py", line 148, in apply_schema
  File "/usr/local/lib/python3.7/site-packages/ccm_extensions-0.1-py3.7.egg/ccm_extensions.py", line 146, in <lambda>
AttributeError: module 'cassandra.connection' has no attribute 'DefaultEndPoint'
```

I removed ccm, ccm-extensions as well as cassandra-driver from pip (both pip2 and pip3) and I installed it all over again.

pip2 gives

```
cassandra-driver         3.24.0           
ccm                      3.1.5            
ccm-extensions           0.1     
```

pip3 gives

```
cassandra-driver         3.16.0      
catdog                   1.0         
ccm                      3.1.5       
ccm-extensions           0.1       
```

**Comment by smiklosovic** [comment]
I had still old version of a driver, there is yet another Python installation of version 3.7 and that one had old version ...
